Repository tb-rules10/Hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#1 Fidget spinner
  fidgetspin.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#2 hacktoberfest2022
  fds1.ipynb
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 Create hello.py
  hello.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 hacktoberfest2022
  GCD.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#3 added hello world C++ program
  Hello_World.cpp
Labels: hacktoberfest, hacktoberfest2022

#6 Create sum.cpp
  sum.cpp
Labels: hacktoberfest

#7 Create helloworld.kotlin
  helloworld.kotlin
Labels: hacktoberfest

#8 Create hello_world.go
  hello_world.go
Labels: hacktoberfest

#9 Create helloworld.scala
  helloworld.scala
Labels: hacktoberfest, hacktoberfest-accepted

#11 Create sum.java
  sum.java
Labels: hacktoberfest-accepted

#12 Create Insertion.java
  Insertion.java
Labels: hacktoberfest

#13 Create HeLlo.kt
  HeLlo.kt
Labels: hacktoberfest, hacktoberfest-accepted

#14 Create hello_world.rs
  hello_world.rs
Labels: hacktoberfest, hacktoberfest-accepted

#15 Create Rana.py
  Rana.py
Labels: hacktoberfest, hacktoberfest-accepted

#16 Hello world in bash
  helloworld.sh
Labels: hacktoberfest, hacktoberfest-accepted

#17 Create hello_world.pas
  hello_world.pas
Labels: hacktoberfest, hacktoberfest-accepted

#18 Hello World in Java
  SumAll.java
Labels: hacktoberfest, hacktoberfest-accepted

#19 Mathematical question
  q5.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create HangmanGame.py
  HangmanGame.py
Labels: hacktoberfest, hacktoberfest-accepted
